worlds:
- putyourworldshere

limit-drops:
  player: true
  container-inventory: true
  minecart-inventory: true
  dispenser: true

prevent-shulkerbox-creative-drops: false

drop-message: "&cInventory drops are not allowed in this world."
